### ISSUE TITLE
Null "browser" values appear to break downstream webpack builds

### ISSUE THREAD

**Issue by jeffbaumes** [vega/vega-canvas#1]
In the [candela](https://github.com/Kitware/candela) library, which depends on vega and uses webpack, we started seeing the following error earlier today:

```
Undefined identifier
/Users/jeff/code/candela/node_modules/enhanced-resolve/lib/Resolver.js:184
	var idxQuery = identifier.indexOf("?");
	                          ^

TypeError: Cannot read property 'indexOf' of null
    at Resolver.parse (/Users/jeff/code/candela/node_modules/enhanced-resolve/lib/Resolver.js:184:28)
```

It is being triggered by some logic in [enhanced-resolve](https://github.com/webpack/enhanced-resolve/blob/master/lib/AliasFieldPlugin.js#L31-L44) when attempting to load `canvas` from `vega-canvas`. The value of `data` is `null` (not `undefined` or `false`), so it passes the checks and gets sent on to lower stacks until it is eventually referenced and gets the `indexOf` error (`doRequest()` is called with the `request` field set to `null`):

```
 31 		var data = typeof data1 !== "undefined" ? data1 : data2;
 32 		if(data === innerRequest) return callback();
 33 		if(data === undefined) return callback();
 34 		if(data === false) {
 35 			var ignoreObj = Object.assign({}, request, {
 36 				path: false
 37 			});
 38 			return callback(null, ignoreObj);
 39 		}
 40 		var obj = Object.assign({}, request, {
 41 			path: request.descriptionFileRoot,
 42 			request: data
 43 		});
 44 		resolver.doResolve(target, obj, "aliased from description file " + request.descriptionFilePath + " with mapping '" + innerRequest + "' to '" + data + "'", createInnerCallback(function(err, result) {
```

I don't know anything about the `browser` field in `package.json`, but this [spec](https://github.com/defunctzombie/package-browser-field-spec) seems to suggest using `false`, and does not mention the use of `null`. Should `null`s be changed to `false` or `undefined` in `package.json` instead to make tools like webpack happy?

That's the best analysis I can do with limited knowledge on the subject.

**Comment by domoritz** [comment]
This is also causing build issues in ipyvega and jupyter renderers.

**Comment by domoritz** [comment]
However, I can compile successfully with webpack 1. #jsproblems
